parameters:
#    store_catalog.example.class: Store\CatalogBundle\Example

services:
#    store_catalog.example:
#        class: %store_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
