parameters:
#    store_main.example.class: Store\MainBundle\Example

services:
#    store_main.example:
#        class: %store_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
